// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramEngine.Data;

#nullable disable

namespace TelegramRoom.Migrations
{
    [DbContext(typeof(TelegramContext))]
    [Migration("20260620160728_BillUnitFkDropLocation")]
    partial class BillUnitFkDropLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.CustomerTelegramContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramContactId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CustomerTelegramContacts");
                });

            modelBuilder.Entity("Library.Models.IdentityUtility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityUtilities");
                });

            modelBuilder.Entity("Library.Models.PcmcBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("AutoSend")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResidentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UnitId");

                    b.ToTable("PcmcBills");
                });

            modelBuilder.Entity("Library.Models.PcmcCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<bool>("ChatImported")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelegramHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("TelegramSessionContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TelegramSessionContactId");

                    b.ToTable("PcmcCustomers");
                });

            modelBuilder.Entity("Library.Models.PcmcCustomerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PcmcCustomerServices");
                });

            modelBuilder.Entity("Library.Models.PcmcProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("AssignedTelegramSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastReminderActivity")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTelegramSessionId");

                    b.ToTable("PcmcProperties");
                });

            modelBuilder.Entity("Library.Models.PcmcService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReminderTemplate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PcmcServices");
                });

            modelBuilder.Entity("Library.Models.PcmcUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("PcmcUnits");
                });

            modelBuilder.Entity("Library.Models.TelegramContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccessHash")
                        .HasColumnType("bigint");

                    b.Property<bool>("Bot")
                        .HasColumnType("boolean");

                    b.Property<bool>("BotChatHistory")
                        .HasColumnType("boolean");

                    b.Property<int?>("BotInfoVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("BotInlineGeo")
                        .HasColumnType("boolean");

                    b.Property<string>("BotInlinePlaceholder")
                        .HasColumnType("text");

                    b.Property<bool>("BotNoChats")
                        .HasColumnType("boolean");

                    b.Property<int>("CheckState")
                        .HasColumnType("integer");

                    b.Property<bool>("Contact")
                        .HasColumnType("boolean");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChat")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("LangCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckStateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastUpdateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Min")
                        .HasColumnType("boolean");

                    b.Property<bool>("MutualContact")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean");

                    b.Property<string>("RestrictionReason")
                        .HasColumnType("text");

                    b.Property<bool>("Self")
                        .HasColumnType("boolean");

                    b.Property<long>("TContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TelegramContacts");
                });

            modelBuilder.Entity("Library.Models.TelegramMessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TranId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelegramMessageLogs");
                });

            modelBuilder.Entity("Library.Models.TelegramSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessHash")
                        .HasColumnType("text");

                    b.Property<bool>("AuthRestart")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoadContacts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TelegramSessions");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionBusiness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<string>("CloudDir")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("TSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TSessionId");

                    b.ToTable("TelegramSessionBusiness");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<long>("TContactId")
                        .HasColumnType("bigint");

                    b.Property<long>("TSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TContactId");

                    b.HasIndex("TSessionId");

                    b.ToTable("TelegramSessionContacts");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<byte[]>("Session")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long?>("TSessionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TSessionId");

                    b.ToTable("TelegramSessionStores");
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSetPwd")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<Guid>("SubJectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Library.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RevokeCount")
                        .HasColumnType("integer");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Library.Models.UserSessionTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId");

                    b.ToTable("UserSessionTenants");
                });

            modelBuilder.Entity("Library.Models.UserSessionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId");

                    b.ToTable("UserSessionTokens");
                });

            modelBuilder.Entity("Library.Models.PcmcBill", b =>
                {
                    b.HasOne("Library.Models.PcmcCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Library.Models.PcmcUnit", "UnitRef")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Customer");

                    b.Navigation("UnitRef");
                });

            modelBuilder.Entity("Library.Models.PcmcCustomer", b =>
                {
                    b.HasOne("Library.Models.PcmcProperty", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.TelegramSessionContact", "TelegramSessionContact")
                        .WithMany()
                        .HasForeignKey("TelegramSessionContactId");

                    b.Navigation("Location");

                    b.Navigation("TelegramSessionContact");
                });

            modelBuilder.Entity("Library.Models.PcmcCustomerService", b =>
                {
                    b.HasOne("Library.Models.PcmcCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.PcmcService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Library.Models.PcmcProperty", b =>
                {
                    b.HasOne("Library.Models.TelegramSession", "AssignedTelegramSession")
                        .WithMany()
                        .HasForeignKey("AssignedTelegramSessionId");

                    b.Navigation("AssignedTelegramSession");
                });

            modelBuilder.Entity("Library.Models.PcmcUnit", b =>
                {
                    b.HasOne("Library.Models.PcmcProperty", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionBusiness", b =>
                {
                    b.HasOne("Library.Models.TelegramSession", "TelegramSession")
                        .WithMany("SessionBusinesses")
                        .HasForeignKey("TSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramSession");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionContact", b =>
                {
                    b.HasOne("Library.Models.TelegramContact", "TelegramContact")
                        .WithMany("SessionContacts")
                        .HasForeignKey("TContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.TelegramSession", "TelegramSession")
                        .WithMany("SessionContacts")
                        .HasForeignKey("TSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramContact");

                    b.Navigation("TelegramSession");
                });

            modelBuilder.Entity("Library.Models.TelegramSessionStore", b =>
                {
                    b.HasOne("Library.Models.TelegramSession", "TelegramSession")
                        .WithMany()
                        .HasForeignKey("TSessionId");

                    b.Navigation("TelegramSession");
                });

            modelBuilder.Entity("Library.Models.UserSession", b =>
                {
                    b.HasOne("Library.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Models.UserSessionTenant", b =>
                {
                    b.HasOne("Library.Models.UserSession", "UserSession")
                        .WithMany("Tenants")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("Library.Models.UserSessionToken", b =>
                {
                    b.HasOne("Library.Models.UserSession", "UserSession")
                        .WithMany("Tokens")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("Library.Models.TelegramContact", b =>
                {
                    b.Navigation("SessionContacts");
                });

            modelBuilder.Entity("Library.Models.TelegramSession", b =>
                {
                    b.Navigation("SessionBusinesses");

                    b.Navigation("SessionContacts");
                });

            modelBuilder.Entity("Library.Models.UserSession", b =>
                {
                    b.Navigation("Tenants");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
